const KEYWORDS = {
    character: [
      "jesus i saw that meme",
      "street cats",
      "ghost of disapproval",
      "bones and botany",
      "stay positive",
      "firstprince pride",
      "little blue flowers s",
      "flowers growing from book",
      "rickroll qr code",
      "cosmic sound",
      "dog distraction",
      "what a time to be alive",
      "radiate positivity",
      "life is short and so am i",
      "hammerhead shark mouse pad",
      "shrek pun",
      "a cure for stupid people",
      "worship coffee",
      "dogtor",
      "black cat",
      "planets colour",
      "yikes",
      "the lovers",
      "plant friends all over print",
      "black cat holding on",
      "yellow cosmos flowers",
      "abduction",
      "travel",
      "nasa retro",
      "tea time",
      "caffeine",
      "beneath the waves",
      "firstprince leaf umbrella",
      "sloth stack",
      "honey bees",
      "opossum live laugh love",
      "watercolor lavender",
      "dance with death",
      "alex",
      "dinosaur illustrations",
      "never better",
      "sneaky cat",
      "salem",
      "black cat with flowers",
      "one mental breakdown later",
      "subtle bi pride flowers",
      "betty white middle finger",
      "corgi set",
      "spooky pals",
      "mason jar with flowers",
      "the future is female",
      "great sushi dragon",
      "the bodacious period",
      "cat in lotus tattoo",
      "enjoy the little things",
      "rad in peace",
      "doggo",
      "soulja boy tweet",
      "rick roll qr",
      "together",
      "blue vinyl record player",
      "the jasmine dragon",
      "bunny in a bottle",
      "faith cross",
      "moon phases",
      "eat the rich frog",
      "kermit meme pack",
      "moon",
      "peace hamster meme",
      "heart lolly",
      "forest mountain horizon",
      "tiny tiny duck",
      "retro mini star pack",
      "seal of approval",
      "pastel books",
      "progress pride flag",
      "neko atsume",
      "visit tatooine",
      "pride hearts",
      "sounds gay im in",
      "black cat pattern",
      "get kraken",
      "equality",
      "silly little toki",
      "silly goose juice dad hat",
      "tiny axolotl",
      "death rides a black cat",
      "flowers",
      "friday",
      "prison mike",
      "galactic deliciousness",
      "peace out dude",
      "death before decaf",
      "smile",
      "vector",
      "many lands under one sun",
      "jellyfish watercolor",
      "night at the museum",
      "kris jenner",
      "another one bites the dust",
      "metamorphora",
      "a frog and his son",
      "happy axolotl",
      "space turtles",
      "kermit meme set",
      "suspicious cats",
      "anatomical heart",
      "oh whale",
      "achieve your dreams",
      "ratatouille",
      "stegaysaurus",
      "psychedelic peace",
      "painted sunflower bouquet",
      "karaoke henry",
      "adolin",
      "the high ground",
      "murder crow",
      "the protector",
      "handdrawn wildflower s",
      "mental health matters flower",
      "we used to live there",
      "caring for your demon cat",
      "cat loaf",
      "alien",
      "chemistry dog meme",
      "honey moon",
      "crying cat croc meme",
      "octopus",
      "roll initiative",
      "catana",
      "tell your cat i said pspsps",
      "cactus",
      "cute soot spirits",
      "harvester of gold",
      "monarch butterfly pack blue",
      "nature guitar",
      "no talk me",
      "it is what it is",
      "you are my sunshine",
      "skateboarding frog",
      "succulents",
      "embrace",
      "moon bay pet blanket",
      "splattered plankton",
      "ask me about my lobotomy",
      "aesthetic rainbow",
      "iced coffee",
      "american shorthair happy",
      "frank ocean",
      "mountains",
      "i heart books",
      "the birches",
      "mental health matters",
      "silly little nathan",
      "death tarot",
      "silly little cfo",
      "japanses ramen noodles bowl",
      "rolls eyes",
      "adventure is out there",
      "dandelion frog",
      "flowery books and tea",
      "vintage book quote",
      "hanging pothos plant",
      "drink cactus juice",
      "succulent plant",
      "ron approves",
      "fireflies framed",
      "shrek",
      "sharks in the light blue",
      "christian quote watercolor",
      "bibble meme",
      "life is short and so am i",
      "waves",
      "the lovers",
      "grizzly bear",
      "baby highland cow",
      "paula deen riding butter",
      "ky promise",
      "dead inside but caffeinated",
      "pudge",
      "boys tears juicebox",
      "meowdy cowboy cat",
      "flower tumblr",
      "insert coin retro arcade",
      "mushrooms and wildflowers",
      "koi fish pack",
      "sea turtle watercolor blue",
      "be kind colorful vintage",
      "floral paw print trio",
      "how to chill like a cat",
      "pride cats",
      "bold and brash",
      "forest moon",
      "royal albert hall teaparty",
      "bee kind",
      "koi fish pond",
      "sell your soul",
      "save ferris campaign",
      "waves",
      "evil eye trio",
      "dinosaur set",
      "encourage mint",
      "yeehaw",
      "the fellowship",
      "k hearts",
      "neon trippy skull",
      "remember why you started",
      "great wave",
      "chicken joe is a vibe",
      "the office",
      "the elder council",
      "corndogs",
      "cephalopod",
      "mandalore all over print",
      "cat reading book",
      "bubble buddy spongebob",
      "this man ate my son",
      "balloon sloth",
      "not today satan",
      "date s",
      "AND YET, DESPITE THE LOOK ON MY FACE, YOU'RE STILL TALKING",
      "WKRP Cincinnati",
      "I Don't Always Mahna Mahna",
      "Childless Cat Ladies Vote Kamala Harris 2024 Election",
      "Norm Macdonald // Classic Vintage Style",
      "VINTAGE FELIX",
      "Kamala Harris 2024",
      "Anthony edwards",
      "He is Rizzin Funny Easter Jesus Playing Basketball Meme",
      "Volume VU Meter Vintage Audio Engineer Recording Studio Gear Head Musician Guitar Shirt",
      "Livin' The Dream, Vintage Styled Distressed",
      "Vintage Republic of Chad Africa African Flag",
      "Globo Gym Purple Cobras - vintage logo",
      "Hawk Tuah Retro Sunset",
      "Jesus Girl | Christian",
      "80s Pet Sematary",
      "Bill and Ted - Be Excellent To Each Other",
      "Creed '24 Take Me Higher Funny Creed 2024",
      "harris-walz",
      "van halen",
      "you missed shot Trump",
      "Buddha : Usachan - Record of Ragnarok",
      "mf doom",
      "Harris Walz Remove Weird Orange Stains",
      "1",
      "Pump it up - Arrows",
      "The Low End Theory",
      "Childless Cat Ladies Vote Kamala Harris 2024 Election",
      "ENHYPEN COLLAGE",
      "anime ramen",
      "Samurai jack",
      "Team Simone Biles Manuel USA Swimming Gymnastics",
      "johnny cash folsom",
      "Holiday Pups",
      "Radioactive dreams",
      "Muscle Rock",
      "LaBelleGiselle",
      "Heroines of Olympus",
      "Taeil NCT",
      "Cute Donkey Dreaming",
      "BITCOIN - TO THE MOON",
      "I'd Rather Be at a STS9 Show",
      "Logo v1 | Muriel's Murders",
      "abstraction #1",
      "Mumford Phys. Ed. Dept.",
      "Read Think Vote",
      "Harris-Walz",
      "I Don't Always Mahna Mahna",
      "I love You To Pizzas",
      "Kamala Harris 2024",
      "Sounds As Worn By Kurt Cobain",
      "Kamala Harris 2024 We Are Not Going Back",
      "Husband And Wife Cruising Partners For Life Retro Vintage",
      "Trump-vance",
      "Volume VU Meter Vintage Audio Engineer Recording Studio Gear Head Musician Guitar Shirt",
      "You Don't Have to Believe in Us - white text",
      "Bikers for Biden Motorcycle Club - Vote Joe 2020",
      "Tee Imagine Daisy Flower Hippie",
      "New logo",
      "Cat",
      "Kamala Harris 2024",
      "OX 45 Malt Liquor",
      "the doobie brothers",
      "That's Not How You Sax, Bro!",
      "Mando's Garage",
      "Kindest Surprise",
      "Cat Ladies For Kamala",
      "I May Have A Touch Of The Tism",
      "Cats Against Trump",
      "Comma-La Kamala",
      "BABY BILLY LIKE",
      "Electricity Will Kill You Kids",
      "I'll Tread Wherever I Want",
      "Calmer Than You Are Funny Walter Sobchak Big Lebowski",
      "Oh Lawd He Treading",
      "Comma La Kamala",
      "Kamala Harris 2024 Cat Lady",
      "Raise the bar",
      "Hope Hate Heal Grow",
      "50 Sally O'Malley",
      "NY METS OMG",
      "Kamala-harris",
      "harris-walz",
      "The Wait",
      "kamala-harris-for-president",
      "FORWARD Kamala Harris Tim Walz FORWARD 2024",
      "beijinho print (not",
      "Kamala Harris For President",
      "Comma-La Kamala",
      "I Don't Have Ducks",
      "sally o'malley I'm 50 i like to kick, streth, and kick!",
      "CYBERTRUCK T-SHIRT",
      "Harris Walz 2024 Boho Groovy Retro Rainbow Kamala Harris 2024",
      "Kamala Harris 2024 Boho Groovy Rainbow",
      "Kamala Harris 2024",
      "Cat Ladies For Kamala",
      "Victim the Dog",
      "'Comma-la' Kamala Harris",
      "Comma La, Kamala Harris",
      "Tracy Chapman vintage",
      "Enso Zen: Tranquility",
      "I Think You Should Leave with Tim Robinson Hot Dog",
      "Elephant",
      "Free Frosty From The Kranks",
      "Eames Dots",
      "Oasis RTC",
      "Art Deco Fresco in Sky Blue and Coral",
      "Diana Ross Vintage Paper",
      "Memphis State Tigers",
      "One last splash mountain",
      "Sally o'malley blue Vintage",
      "The Works",
      "Pee wee herman 80s quote",
      "Let's Be Weird Together - Cats",
      "Its Red Wine Day Every Day",
      "Largo Orchards - Florida's Best Key Lime Pies",
      "The Declaration of Independence",
      "Thumpertown Beach in Eastham, Cape Cod",
      "Marie Antoinette never said that",
      "Sanderson Sisters - Halloween Hocus Pocus",
      "Huck Reading Book",
      "I'll Tread Wherever I Want",
      "Oh Lawd He Treading",
      "Change The World",
      "Subway",
      "Super Star",
      "Ace of Spades",
      "OSRS Fire Cape Pattern",
      "The Mulligans & The Crew",
      "Scorpion Vintage Snowmobiles",
      "Skeleton Knight",
      "Philly Mascots",
      "Comma-La Kamala",
      "I Love Winter Sports",
      "'Comma-la' Kamala Harris",
      "Kindness Peace Equality Love Inclusion Hope Diversity Lgbt",
      "Cat Ladies For Kamala",
      "Rainbow Trout",
      "Wild About Reading Back To School Teacher Books Read",
      "Harris Walz 2024 VP Vice President Funny Cat for Kamala Harris 2024 Election Gifts",
      "Comma La Kamala",
      "Kamala Harris 2024 Boho Groovy Rainbow",
      "Harris Walz 2024",
      "Dark tortoiseshell tortois shell pattern",
      "Kamala 2024 Vote Kamala Harris 2024 Election",
      "Leopard texture",
      "Frankenstrat Guitar Pattern",
      "Suicideboys Vintage",
      "Coors Rodeo Banquet - Cowboy Club - Vintage Retro",
      "Helping the Enemy Used to be Called Treason Now It's Called Being A Republican",
      "Cat selfie with UFO",
      "This was never a long shot Caitlin Clark basketball",
      "Stinkor",
      "80's Boombox Ghettoblaster",
      "Cat Ladies For Kamala",
      "I May Have A Touch Of The Tism",
      "Cats Against Trump",
      "Comma-La Kamala",
      "BABY BILLY LIKE",
      "Electricity Will Kill You Kids",
      "I'll Tread Wherever I Want",
      "Calmer Than You Are Funny Walter Sobchak Big Lebowski",
      "Oh Lawd He Treading",
      "Comma La Kamala",
      "Kamala Harris 2024 Cat Lady",
      "HALAL",
      "Harris Walz 2024",
      "Vintage Kamala Harris 2024",
      "Orange You Glad?",
      "Nashville Minimal Skyline",
      "Betty Boop new 4",
      "Comma-La Kamala",
      "Kamala Harris Tim Walz 2024 Election Democrat",
      "Comma La",
      "Classic Sturgis motorcycle rally the ride the roar the rally in white",
      "Comma La Kamala",
      "'Comma-la' Kamala Harris",
      "Kamala Harris 2024 Boho Groovy Rainbow",
      "Cat Ladies For Kamala",
      "Harris Walz 2024 Boho Groovy Retro Rainbow Kamala Harris 2024",
      "Kamala Harris 2024 Cat Lady",
      "Childless Cat Ladies for Kamala Cat Lady",
      "Electricity Will Kill You Kids",
      "Kamala remove stubborn",
      "Doc Holiday: I'm In My Prime. Tombstone, Movie, Retro, 90s",
      "'This is my second rodeo.' in plain white letters - cos you're not the noob, but barely"
    ]
  };
  
  module.exports = {
    KEYWORDS
  };