const KEYWORDS = {
    character: [
      "spooky pop culture icons",
      "Halloween movie characters",
      "witchy Halloween aesthetics",
      "pumpkin spice pop culture",
      "pop culture Halloween costumes",
      "celebrity Halloween transformations",
      "food art sculptures",
      "culinary-inspired paintings",
      "food-themed installations",
      "vegetable-inspired pottery",
      "dessert-inspired fashion",
      "chocolate-based art",
      "eerie stop-motion cinematography",
      "dark animation techniques",
      "surreal puppet movements",
      "gothic claymation designs",
      "haunted stop-motion animation",
      "creepy puppet choreography",
      "nightmarish puppet designs",
      "spooky marionette concepts",
      "haunted doll aesthetics",
      "twisted puppet tales",
      "social justice movements",
      "activism for equality",
      "human rights campaigns",
      "community-driven change",
      "grassroots activism",
      "election term limits",
      "political career restrictions",
      "legislative service boundaries",
      "fixed-term governance",
      "public office limitations",
      "women’s liberation movement",
      "women’s suffrage history",
      "female empowerment campaigns",
      "gender equality advocacy",
      "women's legal rights",
      "diversity training programs",
      "inclusive workplace strategies",
      "multicultural representation",
      "diversity policies",
      "cultural inclusivity campaigns",
      "climate change awareness",
      "environmental advocacy campaigns",
      "carbon footprint reduction",
      "sustainable living initiatives",
      "climate justice movements",
      "Harvest Moon celebrations",
      "autumn moonlight traditions",
      "lunar festival rituals",
      "celestial harvest symbolism",
      "full moon folklore",
      "Mid-Autumn moon cakes",
      "lantern-lit festivals",
      "moon worship traditions",
      "family reunion celebrations",
      "autumn lantern processions",
      "La Mercè parades",
      "Catalan folk traditions",
      "giant puppet processions",
      "Barcelona street festivals",
      "firework-filled celebrations",
      "Oktoberfest beer culture",
      "traditional Bavarian costumes",
      "German festival foods",
      "folk music gatherings",
      "Munich festival traditions",
      "Regency era fashion",
      "Bridgerton-inspired ballgowns",
      "Regency romance tropes",
      "elegant social soirées",
      "19th-century courtship rituals",
      "vintage aesthetic decor",
      "retro fashion revival",
      "antique-inspired accessories",
      "mid-century modern style",
      "classic Hollywood glam",
      "funny car decals",
      "quirky bumper stickers",
      "sarcastic car slogans",
      "humorous driving quotes",
      "pun-filled sticker designs",
      "magical quest narratives",
      "enchanted adventure stories",
      "fantastical journey themes",
      "wizardly travel companions",
      "epic magical quests",
      "mythical folklore tales",
      "legendary creature myths",
      "ancient mythic heroes",
      "fabled lands",
      "timeless mythic sagas",
      "whimsical gothic creatures",
      "haunting fairytale settings",
      "dark fantasy castles",
      "macabre gothic landscapes",
      "fantastical gothic characters",
      "Autumn Equinox rituals",
      "seasonal harvest festivals",
      "balance of day and night",
      "fall solstice traditions",
      "autumnal celestial celebrations",
      "Bi Visibility Day campaigns",
      "LGBTQ+ awareness events",
      "bisexual pride symbols",
      "celebration of bisexuality",
      "bisexual representation efforts",
      "Hispanic Heritage Month parades",
      "Latino cultural celebrations",
      "Latin American pride events",
      "Spanish-speaking community traditions",
      "multicultural Hispanic narratives",
      "Virgo season horoscopes",
      "astrological Virgo traits",
      "earth sign energies",
      "Virgo zodiac celebrations",
      "Virgo star sign predictions",
      "Libra season horoscopes",
      "balance and harmony energies",
      "air sign influences",
      "Libra astrological traits",
      "Libra zodiac festivals",
      "Halloween candy",
      "Spooky costumes",
      "Jack-o'-lanterns",
      "Ghostly apparitions",
      "Trick-or-treating",
      "Witch's brew",
      "Haunted houses",
      "Pumpkin spice",
      "Cobweb decorations",
      "Monster mash",
      "Vampire fangs",
      "Werewolf howls",
      "Zombie apocalypse",
      "Candy corn",
      "Costume parties",
      "Edible sculptures",
      "Fruit carvings",
      "Vegetable mosaics",
      "Culinary installations",
      "Gastronomic masterpieces",
      "Chocolate artistry",
      "Sugar sculptures",
      "Bread sculptures",
      "Jelly bean portraits",
      "Pancake art",
      "Latte foam designs",
      "Stop-motion puppets",
      "Claymation figures",
      "Skeletal animations",
      "Uncanny valley",
      "Jerky movements",
      "Miniature sets",
      "Time-lapse sequences",
      "Frame-by-frame magic",
      "Surreal landscapes",
      "Twisted fairytales",
      "Marionette strings",
      "Ventriloquist dummies",
      "Haunted dolls",
      "Possessed toys",
      "Sinister clowns",
      "Wooden automatons",
      "Porcelain faces",
      "Grinning masks",
      "Shadow puppets",
      "Social justice",
      "Grassroots movements",
      "Community outreach",
      "Humanitarian aid",
      "Equal rights",
      "Poverty alleviation",
      "Environmental conservation",
      "Education access",
      "Healthcare reform",
      "Voting restrictions",
      "Constitutional amendments",
      "Electoral cycles",
      "Political tenure",
      "Legislative sessions",
      "Governmental checks",
      "Incumbent advantages",
      "Gender equality",
      "Reproductive rights",
      "Pay parity",
      "Maternity leave",
      "Sexual harassment",
      "Glass ceiling",
      "Empowerment initiatives",
      "Inclusive workplaces",
      "Cultural representation",
      "Accessible spaces",
      "Equitable policies",
      "Unconscious bias",
      "Minority voices",
      "Allyship programs",
      "Global warming",
      "Carbon footprint",
      "Renewable energy",
      "Sustainable practices",
      "Eco-friendly alternatives",
      "Greenhouse gases",
      "Ocean acidification",
      "Deforestation impacts",
      "Lunar phases",
      "Celestial beauty",
      "Agricultural abundance",
      "Nocturnal illumination",
      "Tidal influences",
      "Mooncakes",
      "Lantern festivals",
      "Family reunions",
      "Lunar appreciation",
      "Pomegranate symbolism",
      "Catalan traditions",
      "Human towers",
      "Fire runs",
      "Giant papier-mâché figures",
      "Street parades",
      "Bavarian beer tents",
      "Lederhosen",
      "Dirndls",
      "Pretzels",
      "Oompah bands",
      "Regency ballrooms",
      "Empire waistlines",
      "Romantic intrigues",
      "High society gossip",
      "Ornate costumes",
      "Retro aesthetics",
      "Sepia tones",
      "Analog technologies",
      "Nostalgic memorabilia",
      "Antique collectibles",
      "Witty one-liners",
      "Political satire",
      "Pop culture references",
      "Pun-filled phrases",
      "Sarcastic quips",
      "Enchanted forests",
      "Mystical artifacts",
      "Heroic journeys",
      "Dragon lairs",
      "Wizard's towers",
      "Ancient prophecies",
      "Legendary creatures",
      "Folklore traditions",
      "Epic sagas",
      "Cryptic runes",
      "Gothic architecture",
      "Whimsical creatures",
      "Enchanted gardens",
      "Misty moors",
      "Ghostly ballrooms",
      "Autumnal equinox",
      "Harvest celebrations",
      "Seasonal balance",
      "Falling leaves",
      "Mabon rituals",
      "Bisexual pride",
      "LGBTQ+ awareness",
      "Identity spectrum",
      "Bi erasure",
      "Inclusive representation",
      "Latin American heritage",
      "Multicultural celebrations",
      "Salsa rhythms",
      "Mariachi bands",
      "Culinary traditions",
      "Analytical mindsets",
      "Perfectionist tendencies",
      "Earth sign traits",
      "Virgoan practicality",
      "Detail-oriented nature",
      "Diplomatic charm",
      "Balanced perspectives",
      "Artistic inclinations",
      "Libran harmony",
      "Social grace"
    ]
  };
  
  module.exports = {
    KEYWORDS
  };  