const KEYWORDS = {
  character: [
    "aggron retro sprite",
    "indoor cats glossy",
    "indoor cats",
    "mlm pride cerato",
    "hell cerato",
    "a hellish christmas",
    "demamp camp",
    "psychic fire badger butt",
    "jesus the original",
    "endurance",
    "epic",
    "capn",
    "inclusivedinos holiday card",
    "void",
    "merry berries",
    "blue moon",
    "mouthwashing concept design",
    "dragon incubator",
    "goblin breeder",
    "hellhound chewtoy",
    "illithid lover",
    "lizardfolk egglayer",
    "minotaur addict",
    "tentacle plaything",
    "werewolf packmother",
    "christmas hannah waddingham",
    "acoustic song piano flowers",
    "the perfect tree",
    "winter fairies",
    "navigator",
    "married",
    "happy holidays",
    "christmas mug",
    "elafiruze studio bucket hat",
    "elafiruze studio",
    "care and freedom",
    "dave blunts aura shirt",
    "cookie season",
    "holding space",
    "orion",
    "planted",
    "reverie",
    "smoke break",
    "sisters in the shining sun",
    "lovely computer",
    "snaps of venus",
    "robot kisser",
    "lovely polaroid",
    "lovely boombox",
    "lovely walkman",
    "htcc izumi",
    "aussie kangaroo sun",
    "htcc monica",
    "htcc lena",
    "htcc karine transparent",
    "htcc jagoda",
    "htcc nadia",
    "knife frog",
    "maratoneta",
    "loki",
    "everyday smile",
    "loki the drunk angel",
    "no border except collies",
    "jordan riki collage",
    "deep blue",
    "battle card",
    "hp cup",
    "elphybara",
    "capybodger",
    "self carepybara",
    "coquettybara",
    "planted",
    "elder price on the go",
    "blue elise",
    "spn ombre",
    "ski matches",
    "marilyn santa",
    "bite the hand that bleeds",
    "for oj",
    "minecraft tnt",
    "naruto fanart",
    "dragonfly garden",
    "thanksgiving chicken",
    "smiski green figurine",
    "agatha harkness eras",
    "cloud",
    "teto imwatching your stream",
    "bro help teto",
    "african sea lady",
    "flip flop garcia",
    "the rainbow",
    "the thang",
    "draculas juice bucket",
    "sniffa",
    "cute beagle sleeg",
    "xenochill",
    "nick",
    "crow",
    "cute beagle nope not today",
    "dark crimson underwing moth",
    "candy cane otter",
    "aliens are real in the ocean",
    "robin",
    "dog loves christmas",
    "rodent tea party",
    "red salamander dragon",
    "types of dragons",
    "magic mushrooms",
    "cat warriors in a fire",
    "echoes of jenny lind",
    "reylo hair goals",
    "truth and beauty",
    "marc barcelona test",
    "francesco barcelona test",
    "drifter"
  ]
};

module.exports = {
  KEYWORDS
};
