const KEYWORDS = {
  character: [
    "magical girl",
    "shonen protagonist",
    "tsundere",
    "yandere",
    "kuudere",
    "dandere",
    "mecha pilot",
    "schoolgirl",
    "transfer student",
    "childhood friend",
    "rival",
    "sensei",
    "senpai",
    "kouhai",
    "student council president",
    "delinquent",
    "genius prodigy",
    "shrine maiden",
    "idol",
    "neet",
    "hikikomori",
    "otaku",
    "fujoshi",
    "samurai",
    "ninja",
    "ronin",
    "shogun",
    "daimyo",
    "yokai",
    "kitsune",
    "tanuki",
    "tengu",
    "oni",
    "kami",
    "shinigami",
    "esper",
    "alchemist",
    "exorcist",
    "monster hunter",
    "demon slayer",
    "vampire hunter",
    "witch",
    "wizard",
    "summoner",
    "shapeshifter",
    "android",
    "cyborg",
    "space pirate",
    "bounty hunter",
    "assassin",
    "mercenary",
    "martial artist",
    "swordsman",
    "gunslinger",
    "maid",
    "butler",
    "prince",
    "princess",
    "emperor",
    "empress",
    "dragon",
    "phoenix",
    "kappa",
    "neko",
    "kemonomimi",
    "catgirl",
    "nekomata",
    "inugami",
    "spirit medium",
    "onmyoji",
    "time traveler",
    "dimension hopper",
    "alien",
    "superhero",
    "villain",
    "antihero",
    "magical familiar",
    "ghost",
    "zombie",
    "werewolf",
    "vampire",
    "succubus",
    "incubus",
    "angel",
    "fallen angel",
    "demon lord",
    "hero",
    "chosen one",
    "reincarnated person",
    "isekai protagonist",
    "adventurer",
    "guild master",
    "quest giver",
    "merchant",
    "innkeeper",
    "blacksmith",
    "alchemist",
    "bard",
    "rogue",
    "paladin",
    "berserker",
    "monk",
    "cleric",
    "druid",
    "necromancer",
    "summoner",
    "beast tamer",
    "dragon rider",
    "monster girl",
    "monster boy",
    "slime",
    "golem",
    "homunculus",
    "dullahan",
    "banshee",
    "siren",
    "harpy",
    "centaur",
    "mermaid",
    "spirit",
    "elemental",
    "dryad",
    "sylph",
    "undine",
    "gnome",
    "salamander",
    "chimera",
    "griffon",
    "unicorn",
    "pegasus",
    "kirin",
    "yuki-onna",
    "jorogumo",
    "bakeneko",
    "inugami",
    "kodama",
    "kami",
    "youkai",
    "onryo",
    "yurei",
    "zashiki-warashi",
    "oni",
    "ogre",
    "troll",
    "goblin",
    "orc",
    "elf",
    "dark elf",
    "high elf",
    "dwarf",
    "halfling",
    "gnome",
    "faerie",
    "pixie",
    "sprite",
    "nymph",
    "dryad",
    "valkyrie",
    "einherjar",
    "norn",
    "jotun",
    "draugr",
    "revenant",
    "lich",
    "wraith",
    "banshee",
    "poltergeist",
    "doppelganger",
    "mimic",
    "shadow creature",
    "elemental",
    "golem",
    "homunculus",
    "familiar",
    "imp",
    "gremlin",
    "kobold",
    "gnoll",
    "harpy",
    "siren",
    "naga",
    "lamia",
    "centaur",
    "satyr",
    "faun",
    "minotaur",
    "sphinx",
    "chimera",
    "manticore",
    "griffon",
    "hippogriff",
    "pegasus",
    "unicorn",
    "kirin",
    "phoenix",
    "dragon",
    "wyvern",
    "hydra",
    "kraken",
    "leviathan",
    "behemoth",
    "ziz",
    "thunderbird",
    "roc",
    "simurgh",
    "garuda",
    "tengu",
    "kitsune",
    "tanuki",
    "baku",
    "kappa",
    "ningyo",
    "rokuro-kubi",
    "rokurokubi",
    "futakuchi-onna",
    "kuchisake-onna",
    "teke-teke",
    "gashadokuro",
    "jinmenken",
    "nue",
    "tsuchinoko",
    "amabie",
    "amikiri",
    "azukiarai",
    "betobeto-san",
    "funayurei",
    "hitodama",
    "ittan-momen",
    "jubokko",
    "kamaitachi",
    "keukegen",
    "kirin",
    "kosode-no-te",
    "mokumokuren",
    "namahage",
    "nekomata",
    "nuppeppo",
    "nure-onna",
    "nurikabe",
    "okuri-inu",
    "onmoraki",
    "raiju",
    "shachihoko",
    "shirime",
    "shiranui",
    "sunekosuri",
    "tanuki",
    "tatsu",
    "tengu",
    "tsuchigumo",
    "tsukumogami",
    "umibōzu",
    "umibozu",
    "ushi-oni",
    "wanyudo",
    "yatagarasu",
    "yuki-onna"
  ]
};

module.exports = {
  KEYWORDS
};