const KEYWORDS = {
  character: [
    "Plant-Based Seafood Alternatives",
    "High-Protein Snack Bars",
    "Mushroom-Based Coffee",
    "Waterless Skincare Foods",
    "Kelp-Based Snacks",
    "Precision-Fermented Dairy",
    "Alternative Grain Pasta",
    "Upcycled Food Products",
    "Functional Food Gummies",
    "Alcohol-Free Spirits",
    "Plant-Based Charcuterie",
    "Superfood-Infused Chocolates",
    "Adaptogenic Snack Mix",
    "Sustainable Plant Proteins",
    "Gut-Friendly Sauerkraut",
    "Climate-Conscious Coffee",
    "Hybrid Meat Products",
    "Botanical Beverages",
    "Savory Oatmeal Bowls",
    "Protein-Enriched Bread",
    "Innovative Plant-Based Cheese",
    "Lab-Grown Fish",
    "Caffeine-Free Energy Drinks",
    "Smart Hydration Beverages",
    "Omega-3 Rich Plant Oils",
    "Hyper-Local Ingredients",
    "Eco-Friendly Food Packaging",
    "Bioengineered Grains",
    "Prebiotic Smoothies",
    "Zero-Alcohol Wines",
    "Fermented Fruit Condiments",
    "Supergrain Salads",
    "Immune-Boosting Broths",
    "Seaweed Protein Bars",
    "Plant-Based Gelato",
    "Hybrid Dairy Alternatives",
    "Sustainable Spice Blends",
    "Algae Protein Shake",
    "Superfood Acai Bowl",
    "Mango and Basil Sorbet",
    "Spicy Cauliflower Wings",
    "Seaweed Tempura",
    "Root Vegetable Tartine",
    "Organic Barley Soup",
    "Chili Lime Jackfruit Skewers",
    "Avocado Seed Smoothie",
    "Flaxseed Crackers with Dip",
    "Wild Berry Kombucha Float",
    "Nettle Soup",
    "Turmeric Cauliflower Rice Bowl",
    "Gluten-Free Millet Pancakes",
    "Lentil and Quinoa Salad",
    "Sunflower Protein Shake",
    "Kombucha BBQ Sauce Wings",
    "Pineapple Tepache Drink"
  ]
};

module.exports = {
  KEYWORDS
};