const KEYWORDS = {
    character: [
      "humpback whale",
      "blue whale",
      "orca",
      "dolphin",
      "sperm whale",
      "beluga whale",
      "narwhal",
      "gray whale",
      "fin whale",
      "minke whale",
      "sei whale",
      "pilot whale",
      "bottlenose dolphin",
      "harbor porpoise",
      "vaquita",
      "manatee",
      "dugong",
      "spotted dolphin",
      "common dolphin",
      "river dolphin",
      "beaked whale",
      "pygmy sperm whale",
      "commerson's dolphin",
      "false killer whale",
      "melon-headed whale",
      "rough-toothed dolphin",
      "fraser's dolphin",
      "irrawaddy dolphin",
      "atlantic white-sided dolphin",
      "white-beaked dolphin",
      "risso's dolphin",
      "spinner dolphin",
      "striped dolphin",
      "cuvier's beaked whale",
      "baird's beaked whale",
      "ganges river dolphin",
      "indus river dolphin",
      "australian snubfin dolphin",
      "chilean dolphin",
      "hector's dolphin",
      "atlantic humpback dolphin",
      "chinese white dolphin",
      "finless porpoise",
      "dall's porpoise",
      "spectacled porpoise"
    ]
  };
  
  module.exports = {
    KEYWORDS
  };  