const KEYWORDS = {
  character: [
    "abraham van helsing",
    "adolf hitler",
    "aladdin",
    "alan-a-dale",
    "ali baba",
    "anansi",
    "annie oakley",
    "apollo",
    "argonauts",
    "arthur of camelot",
    "athena (folklore)",
    "atlas (mythology)",
    "attila the hun",
    "aunt em & uncle henry",
    "baba yaga",
    "bagheera",
    "baloo",
    "beauty and the beast",
    "beowulf",
    "bigfoot",
    "billy the kid",
    "black dragon society",
    "blackbeard",
    "bloody mary",
    "blue",
    "bo peep",
    "brer rabbit",
    "bride of frankenstein's monster",
    "captain hook",
    "captain kidd (pirate)",
    "captain tootsie",
    "caterpillar",
    "cinderella",
    "claude frollo",
    "cleopatra",
    "clock",
    "conan the barbarian",
    "count of monte cristo",
    "cowardly lion",
    "david (biblical)",
    "dejah thoris",
    "doctor moreau",
    "dorothy",
    "dracula",
    "easter bunny",
    "esmeralda",
    "fairy godmother",
    "father time",
    "faust",
    "frankenstein's monster",
    "friar tuck",
    "fu manchu",
    "genghis khan",
    "georgie porgie",
    "geppetto",
    "geronimo",
    "god",
    "goliath (biblical)",
    "good witch of the north",
    "good witch of the south",
    "hatter",
    "hephaestus",
    "hercules (folklore)",
    "herne the hunter",
    "hippolyta",
    "hugo danner",
    "hunchback of notre-dame",
    "ichabod crane",
    "invisible man (h.g. wells)",
    "irene adler",
    "ivanhoe",
    "jack-in-the-box",
    "jack (beanstalk)",
    "jack frost",
    "jack horner",
    "jack pumpkinhead",
    "jack sprat and his wife",
    "jack and jill",
    "jack the ripper",
    "jacob marley",
    "jane porter",
    "jesse james",
    "jesus",
    "john carter, warlord of mars",
    "john henry",
    "john seward",
    "jonathan harker",
    "julius caesar",
    "kaa",
    "kay",
    "king of hearts",
    "king of truands",
    "kit carson",
    "la of opar",
    "lady of the lake",
    "lancelot",
    "leonardo da vinci",
    "little john",
    "little mermaid",
    "loch ness monster",
    "loki",
    "long john silver",
    "lord ruthven",
    "lucifer",
    "lucy westenra",
    "maid marian",
    "man in the moon",
    "march hare",
    "mars (folklore)",
    "mary & her lamb",
    "mary (nursery rhyme)",
    "medusa",
    "mercury (folklore)",
    "merlin (legend)",
    "merry men",
    "mina murray",
    "miss muffet",
    "mona lisa",
    "mordred",
    "morgan le fay",
    "mother nature",
    "mowgli",
    "mrs. claus",
    "mulan",
    "natty bumppo",
    "neptune",
    "nero",
    "nome king",
    "odin",
    "old king cole",
    "old mother hubbard & her dog",
    "old woman who lived in a shoe",
    "ozma of oz",
    "papa legba",
    "paul bunyan and babe the blue ox (folk legend)",
    "pecos bill",
    "peter the pumpkin-eater",
    "phoebus",
    "pinocchio",
    "pluto of hades",
    "pocahontas",
    "professor moriarty",
    "professor wogglebug",
    "queen of hearts",
    "quincey morris",
    "rasputin",
    "red riding hood",
    "red riding hood's grandmother",
    "red riding hood's lumberjack",
    "robin hood (legend)",
    "robinson crusoe",
    "saint george",
    "samson (biblical)",
    "sancho panza",
    "santa claus",
    "santa claus' reindeer",
    "saw-horse",
    "scarecrow (oz)",
    "scheherazade",
    "shango",
    "shere khan",
    "sheriff of nottingham",
    "sherlock holmes",
    "sigurd",
    "sinbad the sailor",
    "stingy jack",
    "talia",
    "talking cricket",
    "tars tarkas",
    "tarzan",
    "thor (norse god)",
    "three musketeers",
    "tinker bell",
    "tom sawyer",
    "toto",
    "twelve olympians",
    "uncle sam (us government poster)",
    "venus",
    "weird sisters",
    "white rabbit",
    "wicked witch of the east",
    "wicked witch of the north",
    "wicked witch of the west",
    "winged monkeys",
    "wizard of oz",
    "wyatt earp",
    "zeus"
  ]
};

module.exports = {
  KEYWORDS
};